### ISSUE TITLE
Auto-loot

### ISSUE THREAD

**Issue by wpnzach** [Kruithne/EasyDisenchant#1]
Is it possible to automatically grab the loot after the DE?  I know some fishing mods can do this but I didn't know if it was an option with disenchanting.

**Comment by Kruithne** [comment]
In my opinion, this is out of the scope of this add-on. Personally I use my own auto-looter which is a custom mix of of HotLoot.

The reason I'm against putting it as a built-in thing is because it would have to be pretty advanced to cater to the hole it needs to fill, so it seems better to use a purpose-built looting add-on that can be customized by the end user.

**Comment by wpnzach** [comment]
Sure.  I was thinking about it in the context of just the deenchanting addon, as its an extra click for every single item.  I suppose there are other addons that can offer the autoloot functionality for that, though.  I'll look for one of those instead.  Thanks for the work on this addon! :)

**Comment by Kruithne** [comment]
No problems! It was a good suggestion, just don't want to bloat the add-on with functionality people have! The default UI offers auto-looting too.
