### ISSUE TITLE
Add-on No Longer Working

### ISSUE THREAD

**Issue by kentaaa** [Kruithne/EasyDisenchant#13]
ED is one of my favorite, as well as most used, add-on in WoW. I use it religiously due to its ease of use, and its absolutely PERFECT for individuals such as myself who collect bags full of gear from running old raids/dungeons. Unfortunately, as of the last patch update, the add-on no longer works. I've tried everything from disabling/enabling it in game, to uninstalling/reinstalling both the add-on AND the Twitch client itself, When I type in /disenchant, the window opens like normal, however it is completely blank, even though there are DE-able items in my inventory. I've tried on every one of my characters, and I even tried using it on two different computers with the same results. I don't know if the problem lies with me, or the add-on itself, which I'm assuming is the latter, due to the fact that this began as soon as an update was rolled-out. Please let me know if you are aware of this issue, and if it's being (or going to be) fixed in the near future, because being my favorite/most used add-on, I desperately miss it! Thanks so much for your time!

**Comment by Kruithne** [comment]
A breaking issue was reported a while back, and I issued a new build which addressed the problem. As it turns out, the build was sat on Curse marked as 'Alpha', so very few users actually got it!

I've uploaded a new build which, which is currently awaiting approval. Once it goes out, you should be able to update to 1.1.3 and have a working add-on once more.

Thank you for bringing this to my attention, as I was oblivious to the fact the add-on wasn't working for people. Sorry for the issues caused!
